"""
This type stub file was generated by pyright.
"""

from typing import List, Optional
from openbb_terminal.decorators import log_start_end
from openbb_terminal.parent_classes import BaseController

""" Parameters Controller Module """
__docformat__ = ...
logger = ...
class ParametersController(BaseController):
    """Portfolio Optimization Parameters Controller class"""
    CHOICES_COMMANDS = ...
    CHOICES_PARAMS = ...
    PATH = ...
    models = ...
    current_model = ...
    current_file = ...
    def __init__(self, file: str, queue: Optional[List[str]] = ..., params: Optional[dict] = ..., current_model=...) -> None:
        """Constructor"""
        ...
    
    def update_runtime_choices(self): # -> None:
        ...
    
    def print_help(self): # -> None:
        """Print help"""
        ...
    
    def custom_reset(self): # -> list[str] | list[Unknown]:
        """Class specific component of reset command"""
        ...
    
    @log_start_end(log=logger)
    def call_load(self, other_args: List[str]): # -> None:
        """Process load command"""
        ...
    
    @log_start_end(log=logger)
    def call_save(self, other_args: List[str]): # -> None:
        """Process save command"""
        ...
    
    @log_start_end(log=logger)
    def call_clear(self, other_args: List[str]): # -> None:
        """Process set command"""
        ...
    
    @log_start_end(log=logger)
    def call_set(self, other_args: List[str]): # -> None:
        """Process set command"""
        ...
    
    @log_start_end(log=logger)
    def call_arg(self, other_args: List[str]): # -> None:
        """Process arg command"""
        ...
    


