"""
This type stub file was generated by pyright.
"""

import pandas as pd
from openbb_terminal.decorators import check_api_key, log_start_end

"""CoinMarketCap model"""
__docformat__ = ...
logger = ...
FILTERS = ...
sort_map = ...
@log_start_end(log=logger)
@check_api_key(["API_CMC_KEY"])
def get_cmc_top_n(sortby: str = ..., ascend: bool = ...) -> pd.DataFrame:
    """Shows top n coins. [Source: CoinMarketCap]

    Parameters
    ----------
    sortby: str
        Key to sort data. The table can be sorted by every of its columns. Refer to
        Coin Market Cap:s API documentation, see:
        https://coinmarketcap.com/api/documentation/v1/#operation/getV1CryptocurrencyListingsLatest
    ascend: bool
        Whether to sort ascending or descending

    Returns
    -------
    pd.DataFrame
        Top coin on CoinMarketCap

    """
    ...

