"""
This type stub file was generated by pyright.
"""

from typing import List, Optional, Union
from openbb_terminal import OpenBBFigure
from openbb_terminal.decorators import check_api_key, log_start_end

"""NASDAQ Data Link View"""
__docformat__ = ...
logger = ...
@log_start_end(log=logger)
def display_economic_calendar(countries: List[str], start_date: str, end_date: str, limit: int = ..., export: str = ..., sheet_name: Optional[str] = ...) -> None:
    """Display economic calendar for specified country between start and end dates

    Parameters
    ----------
    countries : List[str]
        List of countries to include in calendar.  Empty returns all
    start_date : str
        Start date for calendar
    end_date : str
        End date for calendar
    limit : int
        Limit number of rows to display
    export : str
        Export data to csv or excel file
    """
    ...

@log_start_end(log=logger)
@check_api_key(["API_KEY_QUANDL"])
def display_big_mac_index(country_codes: Optional[List[str]] = ..., raw: bool = ..., export: str = ..., sheet_name: Optional[str] = ..., external_axes: bool = ...) -> Union[OpenBBFigure, None]:
    """Display Big Mac Index for given countries

    Parameters
    ----------
    country_codes : List[str]
        List of country codes (ISO-3 letter country code). Codes available through economy.country_codes().
    raw : bool, optional
        Flag to display raw data, by default False
    export : str, optional
        Format data, by default ""
    external_axes : bool, optional
        Whether to return the figure object or not, by default False
    """
    ...

