"""
This type stub file was generated by pyright.
"""

from typing import Optional
from openbb_terminal.decorators import log_start_end

"""WSJ view """
__docformat__ = ...
logger = ...
@log_start_end(log=logger)
def display_overview(export: str = ..., sheet_name: Optional[str] = ...): # -> None:
    """Market overview with daily change. [Source: Wall St. Journal]

    Parameters
    ----------
    export : str
        Export dataframe data to csv,json,xlsx file
    """
    ...

@log_start_end(log=logger)
def display_indices(export: str = ..., sheet_name: Optional[str] = ...): # -> None:
    """US indices. [Source: Wall St. Journal]

    Parameters
    ----------
    export : str
        Export dataframe data to csv,json,xlsx file
    """
    ...

@log_start_end(log=logger)
def display_futures(export: str = ..., sheet_name: Optional[str] = ...): # -> None:
    """Futures/Commodities. [Source: Wall St. Journal]

    Parameters
    ----------
    export : str
        Export dataframe data to csv,json,xlsx file
    """
    ...

@log_start_end(log=logger)
def display_usbonds(export: str = ..., sheet_name: Optional[str] = ...): # -> None:
    """US bonds. [Source: Wall St. Journal]

    Parameters
    ----------
    export : str
        Export dataframe data to csv,json,xlsx file
    """
    ...

@log_start_end(log=logger)
def display_glbonds(export: str = ..., sheet_name: Optional[str] = ...): # -> None:
    """Global bonds. [Source: Wall St. Journal]

    Parameters
    ----------
    export : str
        Export dataframe data to csv,json,xlsx file
    """
    ...

@log_start_end(log=logger)
def display_currencies(export: str = ..., sheet_name: Optional[str] = ...): # -> None:
    """Display currencies. [Source: Wall St. Journal]

    Parameters
    ----------
    export : str
        Export dataframe data to csv,json,xlsx file
    """
    ...

