"""
This type stub file was generated by pyright.
"""

"""Hedge model"""
__docformat__ = ...
def calc_hedge(portfolio_option_amount: float = ..., side: str = ..., greeks: dict = ..., sign: int = ...): # -> tuple[Any, Any, Unknown, bool]:
    """Determine the hedge position and the weights within each option and
    underlying asset to hold a neutral portfolio

    Parameters
    ----------
    portfolio_option_amount: float
        Number to show
    side: str
        Whether you have a Call or Put instrument
    greeks: dict
        Dictionary containing delta, gamma and vega values for the portfolio and option A and B. Structure is
        as follows: {'Portfolio': {'Delta': VALUE, 'Gamma': VALUE, 'Vega': VALUE}} etc
    sign: int
        Whether you have a long (1) or short (-1) position

    Returns
    -------
    option A weight: float
    option B weight: float
    portfolio weight: float
    is_singular: boolean
    """
    ...

def add_hedge_option(price: float = ..., implied_volatility: float = ..., strike: float = ..., days: float = ..., sign: int = ...) -> tuple:
    """Determine the delta, gamma and vega value of the portfolio and/or options.

    Parameters
    ----------
    price: float
        The price.
    implied_volatility: float
        The implied volatility.
    strike: float
        The strike price.
    days: float
        The amount of days until expiration. Use annual notation thus a month would be 30 / 360.
    sign: int
        Whether you have a long (1) or short (-1) position

    Returns
    -------
    delta: float
    gamma: float
    portfolio: float
    """
    ...

def calc_delta(asset_price: float = ..., asset_volatility: float = ..., strike_price: float = ..., time_to_expiration: float = ..., risk_free_rate: float = ..., sign: int = ...): # -> Any | NDArray[Any] | NDArray[signedinteger[Any]]:
    """The first-order partial-derivative with respect to the underlying asset of the Black-Scholes
    equation is known as delta. Delta refers to how the option value changes when there is a change in
    the underlying asset price. Multiplying delta by a +-$1 change in the underlying asset, holding all other
    parameters constant, will give you the new value of the option. Delta will be positive for long call and
    short put positions, negative for short call and long put positions.

    Parameters
    ----------
    asset_price: int
        The price.
    asset_volatility: float
        The implied volatility.
    strike_price: float
        The strike price.
    time_to_expiration: float
        The amount of days until expiration. Use annual notation thus a month would be 30 / 360.
    risk_free_rate: float
        The risk free rate.
    sign: int
        Whether you have a long (1) or short (-1) position

    Returns
    -------
    delta: float
        Returns the value for the delta.
    """
    ...

def calc_gamma(asset_price: float = ..., asset_volatility: float = ..., strike_price: float = ..., time_to_expiration: float = ..., risk_free_rate: float = ...): # -> Any | NDArray[floating[Any]]:
    """The second-order partial-derivative with respect to the underlying asset of the Black-Scholes equation
    is known as gamma. Gamma refers to how the option’s delta changes when there is a change in the underlying
    asset price. Multiplying gamma by a +-$1 change in the underlying asset, holding all other parameters constant,
    will give you the new value of the option’s delta. Essentially, gamma is telling us the rate of change of delta
    given a +-1 change in the underlying asset price. Gamma is always positive for long positions and
    negative for short positions.

    Parameters
    ----------
    asset_price: int
        The price.
    asset_volatility: float
        The implied volatility.
    strike_price: float
        The strike price.
    time_to_expiration: float
        The amount of days until expiration. Use annual notation thus a month would be 30 / 360.
    risk_free_rate: float
        The risk free rate.

    Returns
    -------
    gamma: float
        Returns the value for the gamma.
    """
    ...

def calc_vega(asset_price: float = ..., asset_volatility: float = ..., strike_price: float = ..., time_to_expiration: float = ..., risk_free_rate: float = ...): # -> Any | NDArray[floating[Any]]:
    """The first-order partial-derivative with respect to the underlying asset volatility of
    the Black-Scholes equation is known as vega. Vega refers to how the option value
    changes when there is a change in the underlying asset volatility. Multiplying vega by
    a +-1% change in the underlying asset volatility, holding all other parameters constant, will give
    you the new value of the option. Vega will be positive for long positions and negative for short positions.

    Parameters
    ----------
    asset_price: int
        The price.
    asset_volatility: float
        The implied volatility.
    strike_price: float
        The strike price.
    time_to_expiration: float
        The amount of days until expiration. Use annual notation thus a month would be 30 / 360.
    risk_free_rate: float
        The risk free rate.

    Returns
    -------
    vega: float
        Returns the value for the gamma.
    """
    ...

