"""
This type stub file was generated by pyright.
"""

import pandas as pd
from typing import Any, Optional

"""Optimization helpers"""
__docformat__ = ...
def dict_to_df(d: dict) -> pd.DataFrame:
    """Convert a dictionary to a DataFrame

    Parameters
    ----------
    d : dict
        Dictionary to convert

    Returns
    -------
    pd.DataFrame
        DataFrame with dictionary
    """
    ...

def validate_risk_measure(risk_measure: str, warning: bool = ...) -> str:
    """Check that the risk measure selected is valid

    Parameters
    ----------
    risk_measure : str
        Risk measure to check

    Returns
    -------
    str
        Validated risk measure
    """
    ...

def get_kwarg(key: str, kwargs: dict, default: Optional[Any] = ...) -> Any:
    """Get a key from kwargs

    If key is in kwargs, returns it.
    Otherwise, if default provided, returns it.
    Otherwise, if key is in OPTIMIZATION_PARAMETERS, returns it.

    Parameters
    ----------
    key : str
        The key to be searched
    kwargs : dict
        The kwargs to be searched
    default : Any
        The default value to be returned if the key is not found

    Returns
    -------
    Any
        The value of the key if it exists, else None
    """
    ...

