"""
This type stub file was generated by pyright.
"""

import pandas as pd
from typing import Optional
from openbb_terminal.decorators import log_start_end

""" Nasdaq Model """
__docformat__ = ...
logger = ...
FORM_GROUP = ...
@log_start_end(log=logger)
def get_sec_filings(symbol: str, limit: int = ..., year: Optional[int] = ..., form_group: Optional[str] = ...) -> pd.DataFrame:
    """Get SEC filings for a given stock ticker. [Source: Nasdaq]

    Parameters
    ----------
    symbol : str
        Stock ticker symbol
    limit : int
        The number of filings to return
    year: Optional[int]
        The year to grab from. The year will be ignored if form_group is not specified
    form_group: Optional[str]
        The form type to filter for:
        Choose from: annual, quarterly, proxies, insiders, 8-K, registrations, comments

    Returns
    -------
    df_financials : pd.DataFrame
        SEC filings data
    """
    ...

