"""
This type stub file was generated by pyright.
"""

from typing import Optional
from openbb_terminal.decorators import log_start_end

"""Nasdaq View """
__docformat__ = ...
logger = ...
@log_start_end(log=logger)
def sec_filings(symbol: str, limit: int = ..., export: str = ..., sheet_name: Optional[str] = ..., year: Optional[int] = ..., form_group: Optional[str] = ...): # -> None:
    """Display SEC filings for a given stock ticker. [Source: Nasdaq]

    Parameters
    ----------
    symbol: str
        Stock ticker symbol
    limit: int
        Number of ratings to display
    export: str
        Export dataframe data to csv,json,xlsx file
    sheet_name: str
        Optionally specify the name of the sheet the data is exported to.
    year: Optional[int]
        The year to grab from. The year will be ignored if form_group is not specified
    form_group: Optional[str]
        The form type to filter for:
        Choose from: annual, quarterly, proxies, insiders, 8-K, registrations, comments
    """
    ...

