"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import List, Optional

def save_session(data: dict, file_path: Path = ...): # -> None:
    """Save the login info to a file.

    Parameters
    ----------
    data : dict
        The data to write.
    file_path : Path
        The file path.
    """
    ...

def get_session(file_path: Path = ...) -> dict:
    """Get the session info from the file.

    Parameters
    ----------
    file_path : Path
        The file path.

    Returns
    -------
    dict
        The session info.
    """
    ...

def remove(path: Path) -> bool:
    """Remove path.

    Parameters
    ----------
    path : Path
        The file path.

    Returns
    -------
    bool
        The status of the removal.
    """
    ...

def update_flair(username: str): # -> None:
    """Update the flair.

    Parameters
    ----------
    username : str
        The username.
    """
    ...

def apply_configs(configs: dict): # -> None:
    """Apply configurations.

    Parameters
    ----------
    configs : dict
        The configurations.
    """
    ...

def set_credentials_from_hub(configs: dict): # -> None:
    """Set credentials from hub.

    Parameters
    ----------
    configs : dict
        The configurations.
    """
    ...

def set_preferences_from_hub(configs: dict, fields: Optional[List[str]] = ...): # -> None:
    """Set preferences from hub.

    Parameters
    ----------
    configs : dict
        The configurations.
    fields : Optional[List[str]]
        The fields to set, if None, all fields will be set.
    """
    ...

def set_rich_style_from_hub(configs: dict): # -> None:
    """Set rich style from hub.

    Parameters
    ----------
    configs : dict
        The configurations.
    """
    ...

def set_chart_style_from_hub(configs: dict): # -> None:
    """Set chart style from hub.

    Parameters
    ----------
    configs : dict
        The configurations.
    """
    ...

def set_table_style_from_hub(configs: dict): # -> None:
    """Set table style from hub.

    Parameters
    ----------
    configs : dict
        The configurations.
    """
    ...

def set_sources_from_hub(configs: dict): # -> None:
    """Set sources from hub.

    Parameters
    ----------
    configs : dict
        The configurations.
    """
    ...

