"""
This type stub file was generated by pyright.
"""

from enum import Enum
from typing import Any, Dict, Optional

class LoginStatus(Enum):
    SUCCESS = ...
    FAILED = ...
    NO_RESPONSE = ...
    UNAUTHORIZED = ...


def create_session(email: str, password: str, save: bool) -> Dict[Any, Any]:
    """Create a session.

    Parameters
    ----------
    email : str
        The email.
    password : str
        The password.
    save : bool
        Save the session.
    """
    ...

def create_session_from_token(token: str, save: bool) -> Dict[Any, Any]:
    """Create a session from token.

    Parameters
    ----------
    token : str
        The token.
    save : bool
        Save the session.
    """
    ...

def login(session: Dict, remember: bool = ...) -> LoginStatus:
    """Login and load user info.

    Parameters
    ----------
    session : dict
        The session info.
    remember : bool, optional
        Remember the session, by default False
    """
    ...

def download_and_save_routines(auth_header: str): # -> None:
    """Download and save routines.

    Parameters
    ----------
    auth_header : str
        The authorization header, e.g. "Bearer <token>".
    """
    ...

def update_backend_sources(auth_header, configs, silent: bool = ...): # -> None:
    """Update backend sources if new source or command path available.

    Parameters
    ----------
    auth_header : str
        The authorization header, e.g. "Bearer <token>".
    configs : Dict
        Dictionary with configs
    silent : bool
        Whether to silence the console output, by default True
    """
    ...

def logout(auth_header: Optional[str] = ..., token: Optional[str] = ..., cls: bool = ...): # -> None:
    """Logout and clear session.

    Parameters
    ----------
    auth_header : str, optional
        The authorization header, e.g. "Bearer <token>".
    token : str, optional
        The token to delete.
        In the terminal we want to delete the current session, so we use the user own token.
    cls : bool
        Clear the screen.
    """
    ...

