"""
This type stub file was generated by pyright.
"""

import pandas as pd
from openbb_terminal.decorators import log_start_end

""" Interactive Broker Model """
__docformat__ = ...
logger = ...
@log_start_end(log=logger)
def get_cost_to_borrow() -> pd.DataFrame:
    """Get stocks with highest cost to borrow [Source: Interactive Broker]

    Returns
    -------
    pd.DataFrame
        Cost to borrow
    """
    ...

