"""
This type stub file was generated by pyright.
"""

import pandas as pd
from typing import Optional

logger = ...
def check_columns(data: pd.DataFrame, high: bool = ..., low: bool = ..., close: bool = ...) -> Optional[str]:
    """Returns the close columns, or None if the dataframe does not have required columns

    Parameters
    ----------
    data: pd.DataFrame
        The dataframe to check
    high: bool
        Whether to check for high column
    low: bool
        Whether to check for low column
    close: bool
        Whether to check for close column

    Returns
    -------
    Optional[str]
        The name of the close column, none if df is invalid

    """
    ...

