"""
This type stub file was generated by pyright.
"""

import pandas as pd
from openbb_terminal.decorators import log_start_end

"""Volume Technical Analysis"""
__docformat__ = ...
logger = ...
@log_start_end(log=logger)
def ad(data: pd.DataFrame, use_open: bool = ...) -> pd.DataFrame:
    """Calculate AD technical indicator

    Parameters
    ----------
    data : pd.DataFrame
        Dataframe of prices with OHLC and Volume
    use_open : bool
        Whether to use open prices

    Returns
    -------
    pd.DataFrame
        Dataframe with technical indicator
    """
    ...

@log_start_end(log=logger)
def adosc(data: pd.DataFrame, use_open: bool = ..., fast: int = ..., slow: int = ...) -> pd.DataFrame:
    """Calculate AD oscillator technical indicator

    Parameters
    ----------
    data : pd.DataFrame
        Dataframe of OHLC prices
    use_open : bool
        Whether to use open prices
    fast: int
        Fast value
    slow: int
        Slow value

    Returns
    -------
    pd.DataFrame
        Dataframe with technical indicator
    """
    ...

@log_start_end(log=logger)
def obv(data: pd.DataFrame) -> pd.DataFrame:
    """On Balance Volume

    Parameters
    ----------
    data: pd.DataFrame
        Dataframe of OHLC prices

    Returns
    -------
    pd.DataFrame
        Dataframe with technical indicator
    """
    ...

