"""
This type stub file was generated by pyright.
"""

import pandas as pd
from openbb_terminal.decorators import log_start_end

"""Robinhood Model"""
__docformat__ = ...
logger = ...
dt_format = ...
@log_start_end(log=logger)
def login(): # -> None:
    """Robinhood login"""
    ...

@log_start_end(log=logger)
def logoff(): # -> None:
    """Robinhood logoff"""
    ...

@log_start_end(log=logger)
def get_holdings() -> pd.DataFrame:
    """Return Robinhood holdings

    Returns
    -------
    pd.DataFrame
        Robinhood holdings
    """
    ...

@log_start_end(log=logger)
def rh_positions_to_df(holds: dict) -> pd.DataFrame:
    """Process robinhood holdings to dataframe

    Parameters
    ----------
    holds : dict
        Dictionary from robin_stocks

    Returns
    -------
    pd.DataFrame
        Processed dataframe of holdings
    """
    ...

@log_start_end(log=logger)
def get_historical(interval: str = ..., window: str = ...) -> pd.DataFrame:
    """Get historical portfolio in candle form

    Parameters
    ----------
    interval : str, optional
        Interval for robinhood (candle width), by default "day"
    window : str, optional
        Lookback to get portfolio history, by default "3month"

    Returns
    -------
    pd.DataFrame
        Historical portfolio with OHLC variables
    """
    ...

