"""
This type stub file was generated by pyright.
"""

from pydantic.dataclasses import dataclass as pydanticdataclass

dc = ...
CredentialsModel = pydanticdataclass(dc, config=dict(validate_assignment=True, frozen=True))
