"""
This type stub file was generated by pyright.
"""

from typing import Optional
from openbb_terminal.decorators import log_start_end

"""Tradingview view"""
__docformat__ = ...
logger = ...
@log_start_end(log=logger)
def print_recommendation(symbol: str, screener: str = ..., exchange: str = ..., interval: str = ..., export: str = ..., sheet_name: Optional[str] = ...): # -> None:
    """Print tradingview recommendation based on technical indicators

    Parameters
    ----------
    symbol : str
        Ticker symbol to get tradingview recommendation based on technical indicators
    screener : str
        Screener based on tradingview docs https://python-tradingview-ta.readthedocs.io/en/latest/usage.html
    exchange: str
        Exchange based on tradingview docs https://python-tradingview-ta.readthedocs.io/en/latest/usage.html
    interval: str
        Interval time to check technical indicators and correspondent recommendation
    sheet_name: str
        Optionally specify the name of the sheet the data is exported to.
    export: str
        Format of export file
    """
    ...

