"""
This type stub file was generated by pyright.
"""

from openbb_terminal.decorators import check_api_key, log_start_end

"""AlphaVantage Forex View."""
__docformat__ = ...
logger = ...
@log_start_end(log=logger)
@check_api_key(["API_KEY_ALPHAVANTAGE"])
def display_quote(to_symbol: str = ..., from_symbol: str = ...): # -> None:
    """Display current forex pair exchange rate.

    Parameters
    ----------
    to_symbol : str
        To symbol
    from_symbol : str
        From forex symbol
    """
    ...

