"""
This type stub file was generated by pyright.
"""

from abc import abstractmethod
from typing import Dict, NamedTuple
from langchain.schema import BaseOutputParser

class AutoGPTAction(NamedTuple):
    """Action returned by AutoGPTOutputParser."""
    name: str
    args: Dict
    ...


class BaseAutoGPTOutputParser(BaseOutputParser):
    """Base Output parser for AutoGPT."""
    @abstractmethod
    def parse(self, text: str) -> AutoGPTAction:
        """Return AutoGPTAction"""
        ...
    


def preprocess_json_input(input_str: str) -> str:
    """Preprocesses a string to be parsed as json.

    Replace single backslashes with double backslashes,
    while leaving already escaped ones intact.

    Args:
        input_str: String to be preprocessed

    Returns:
        Preprocessed string
    """
    ...

class AutoGPTOutputParser(BaseAutoGPTOutputParser):
    """Output parser for AutoGPT."""
    def parse(self, text: str) -> AutoGPTAction:
        ...
    


