"""
This type stub file was generated by pyright.
"""

from typing import List, Optional
from openbb_terminal.decorators import log_start_end

""" Comparison Analysis Marketwatch View """
__docformat__ = ...
logger = ...
@log_start_end(log=logger)
def display_income_comparison(symbols: List[str], timeframe: str = ..., quarter: bool = ..., export: str = ..., sheet_name: Optional[str] = ...): # -> None:
    """Display income data. [Source: Marketwatch].

    Parameters
    ----------
    symbols : List[str]
        List of tickers to compare. Enter tickers you want to see as shown below:
        ["TSLA", "AAPL", "NFLX", "BBY"]
        You can also get a list of comparable peers with
        finnhub_peers(), finviz_peers(), polygon_peers().
    timeframe : str
        What year to look at
    quarter : bool, optional
        Whether to use quarterly statements, by default False
    export : str, optional
        Format to export data
    """
    ...

@log_start_end(log=logger)
def display_balance_comparison(symbols: List[str], timeframe: str = ..., quarter: bool = ..., export: str = ..., sheet_name: Optional[str] = ...): # -> None:
    """Compare balance between companies. [Source: Marketwatch]

    Parameters
    ----------
    symbols : List[str]
        List of tickers to compare. Enter tickers you want to see as shown below:
        ["TSLA", "AAPL", "NFLX", "BBY"]
        You can also get a list of comparable peers with
        finnhub_peers(), finviz_peers(), polygon_peers().
    timeframe : str
        What year to look at
    quarter : bool, optional
        Whether to use quarterly statements, by default False
    export : str, optional
        Format to export data
    """
    ...

@log_start_end(log=logger)
def display_cashflow_comparison(symbols: List[str], timeframe: str = ..., quarter: bool = ..., export: str = ..., sheet_name: Optional[str] = ...): # -> None:
    """Compare cashflow between companies. [Source: Marketwatch]

    Parameters
    ----------
    symbols : List[str]
        List of tickers to compare. Enter tickers you want to see as shown below:
        ["TSLA", "AAPL", "NFLX", "BBY"]
        You can also get a list of comparable peers with
        finnhub_peers(), finviz_peers(), polygon_peers().
    timeframe : str
        What year/quarter to look at
    quarter : bool, optional
        Whether to use quarterly statements, by default False
    export : str, optional
        Format to export data
    """
    ...

