"""
This type stub file was generated by pyright.
"""

from typing import List

"""CA SDK Helpers."""
__docformat__ = ...
def get_similar(symbol: str, source=...) -> List[str]:
    """Find similar tickers to a given symbol.

    Parameters
    ----------
    symbol : str
        Symbol to find similar tickers to.
    source : str, optional
        Source to get data for, by default "Finviz".  Can be "Finviz", "Polygon", "Finnhub", or "TSNE"

    Returns
    -------
    List[str]
       List of similar tickers.

    Examples
    --------
    To get similar tickers to AAPL from Finviz:
    >>> from openbb_terminal.sdk import openbb
    >>> similar_tickers = openbb.stocks.ca.similar("AAPL")

    To use our custom TSNE model for similar tickers in the SP500:
    >>> similar_tickers = openbb.stocks.ca.similar("AAPL", source="TSNE")
    """
    ...

