"""
This type stub file was generated by pyright.
"""

from typing import Dict, List, Optional
from openbb_terminal.decorators import check_api_key, log_start_end

""" FRED view """
__docformat__ = ...
logger = ...
ice_bofa_path = ...
commercial_paper_path = ...
spot_rates_path = ...
ID_TO_NAME_ESTR = ...
ID_TO_NAME_SOFR = ...
ID_TO_NAME_SONIA = ...
ID_TO_NAME_AMERIBOR = ...
ID_TO_NAME_FED = ...
ID_TO_NAME_DWPCR = ...
ID_TO_NAME_TMC = ...
ID_TO_NAME_FFRMC = ...
ID_TO_NAME_SECONDARY = ...
ID_TO_NAME_TIPS = ...
ID_TO_NAME_CMN = ...
ID_TO_NAME_TBFFR = ...
NAME_TO_ID_PROJECTION = ...
NAME_TO_ID_ECB = ...
MOODY_TO_OPTIONS: Dict[str, Dict] = ...
@log_start_end(log=logger)
@check_api_key(["API_FRED_KEY"])
def plot_estr(parameter: str = ..., start_date: Optional[str] = ..., end_date: Optional[str] = ..., export: str = ..., sheet_name: str = ..., external_axes: bool = ...): # -> OpenBBFigure | None:
    """Plot Euro Short-Term Rate (ESTR)

    Parameters
    ----------
    parameter: str
        FRED ID of ESTR data to plot, options: ['ECBESTRVOLWGTTRMDMNRT',
        'ECBESTRTOTVOL', 'ECBESTRNUMTRANS', 'ECBESTRRT75THPCTVOL',
        'ECBESTRNUMACTBANKS', 'ECBESTRSHRVOL5LRGACTBNK', 'ECBESTRRT25THPCTVOL']
    start_date: Optional[str]
        Start date, formatted YYYY-MM-DD
    end_date: Optional[str]
        End date, formatted YYYY-MM-DD
    sheet_name: str
        Optionally specify the name of the sheet the data is exported to.
    export: str
        Export data to csv or excel file
    external_axes : bool, optional
        Whether to return the figure object or not, by default False
    """
    ...

@log_start_end(log=logger)
@check_api_key(["API_FRED_KEY"])
def plot_sofr(parameter: str = ..., start_date: Optional[str] = ..., end_date: Optional[str] = ..., export: str = ..., sheet_name: str = ..., external_axes: bool = ...): # -> OpenBBFigure | None:
    """Plot Secured Overnight Financing Rate (SOFR)

    Parameters
    ----------
    parameter: str
        FRED ID of SOFR data to plot, options: ['SOFR', 'SOFR30DAYAVG', 'SOFR90DAYAVG', 'SOFR180DAYAVG', 'SOFRINDEX']
    start_date: Optional[str]
        Start date, formatted YYYY-MM-DD
    end_date: Optional[str]
        End date, formatted YYYY-MM-DD
    sheet_name: str
        Optionally specify the name of the sheet the data is exported to.
    export: str
        Export data to csv or excel file
    external_axes : bool, optional
        Whether to return the figure object or not, by default False
    """
    ...

@log_start_end(log=logger)
@check_api_key(["API_FRED_KEY"])
def plot_sonia(parameter: str = ..., start_date: Optional[str] = ..., end_date: Optional[str] = ..., export: str = ..., sheet_name: str = ..., external_axes: bool = ...): # -> OpenBBFigure | None:
    """Plot Sterling Overnight Index Average (SONIA)

    Parameters
    ----------
    parameter: str
        FRED ID of SONIA data to plot, options: ['IUDSOIA', 'IUDZOS2',
        'IUDZLS6', 'IUDZLS7', 'IUDZLS8', 'IUDZLS9', 'IUDZLT2']
    start_date: Optional[str]
        Start date, formatted YYYY-MM-DD
    end_date: Optional[str]
        End date, formatted YYYY-MM-DD
    export: str
        Export data to csv or excel file
    external_axes : bool, optional
        Whether to return the figure object or not, by default False
    """
    ...

@log_start_end(log=logger)
@check_api_key(["API_FRED_KEY"])
def plot_ameribor(parameter: str = ..., start_date: Optional[str] = ..., end_date: Optional[str] = ..., export: str = ..., sheet_name: str = ..., external_axes: bool = ...): # -> OpenBBFigure | None:
    """Plot American Interbank Offered Rate (AMERIBOR)

    Parameters
    ----------
    parameter: str
        FRED ID of AMERIBOR data to plot, options: ['AMERIBOR', 'AMBOR30T',
        'AMBOR90T', 'AMBOR1W', 'AMBOR1M', 'AMBOR3M', 'AMBOR6M', 'AMBOR1Y',
        'AMBOR2Y', 'AMBOR30', 'AMBOR90']
    start_date: Optional[str]
        Start date, formatted YYYY-MM-DD
    end_date: Optional[str]
        End date, formatted YYYY-MM-DD
    export: str
        Export data to csv or excel file
    external_axes : bool, optional
        Whether to return the figure object or not, by default False
    """
    ...

@log_start_end(log=logger)
@check_api_key(["API_FRED_KEY"])
def plot_fftr(start_date: Optional[str] = ..., end_date: Optional[str] = ..., export: str = ..., sheet_name: str = ..., external_axes: bool = ...): # -> OpenBBFigure | None:
    """Plot Federal Funds Target Range.

    A bank rate is the interest rate a nation's central bank charges to its domestic banks to borrow money. The rates
    central banks charge are set to stabilize the economy. In the United States, the Federal Reserve System's Board
    of Governors set the bank rate, also known as the discount rate.

    Parameters
    ----------
    start_date: Optional[str]
        Start date, formatted YYYY-MM-DD
    end_date: Optional[str]
        End date, formatted YYYY-MM-DD
    export: str
        Export data to csv or excel file
    external_axes : bool, optional
        Whether to return the figure object or not, by default False
    """
    ...

@log_start_end(log=logger)
@check_api_key(["API_FRED_KEY"])
def plot_fed(parameter: str = ..., start_date: Optional[str] = ..., end_date: Optional[str] = ..., overnight: bool = ..., quantiles: bool = ..., target: bool = ..., raw: bool = ..., export: str = ..., sheet_name: str = ..., external_axes: bool = ..., limit: int = ...): # -> OpenBBFigure | None:
    """Plot Effective Federal Funds Rate.

    A bank rate is the interest rate a nation's central bank charges to its domestic banks to borrow money. The rates
    central banks charge are set to stabilize the economy. In the United States, the Federal Reserve System's Board
    of Governors set the bank rate, also known as the discount rate.

    Parameters
    ----------
    parameter: str
        FRED ID of EFFER data to plot, options: ['EFFR', 'EFFRVOL', 'EFFR1', 'EFFR25', 'EFFR75', 'EFFR99']
    start_date: Optional[str]
        Start date, formatted YYYY-MM-DD
    end_date: Optional[str]
        End date, formatted YYYY-MM-DD
    overnight: bool
        Whether you want to plot the Overnight Banking Federal Rate
    quantiles: bool
        Whether you want to see the 1, 25, 75 and 99 percentiles
    target: bool
        Whether you want to see the high and low target range
    raw : bool
        Show raw data
    export: str
        Export data to csv or excel file
    sheet_name: str
        Optionally specify the name of the sheet the data is exported to.
    external_axes : bool, optional
        Whether to return the figure object or not, by default False
    """
    ...

@log_start_end(log=logger)
@check_api_key(["API_FRED_KEY"])
def plot_iorb(start_date: Optional[str] = ..., end_date: Optional[str] = ..., export: str = ..., sheet_name: str = ..., external_axes: bool = ...): # -> OpenBBFigure | None:
    """Plot Interest Rate on Reserve Balances.

    Parameters
    ----------
    start_date: Optional[str]
        Start date, formatted YYYY-MM-DD
    end_date: Optional[str]
        End date, formatted YYYY-MM-DD
    export: str
        Export data to csv or excel file
    external_axes : bool, optional
        Whether to return the figure object or not, by default False
    """
    ...

@log_start_end(log=logger)
@check_api_key(["API_FRED_KEY"])
def plot_projection(long_run: bool = ..., raw: bool = ..., export: str = ..., sheet_name: str = ..., external_axes: bool = ...): # -> OpenBBFigure | None:
    """Plot the Federal Reserve's projection of the federal funds rate.

    Parameters
    ----------
    long_run: str
        Whether to plot the long run projection.
    export: str
        Export data to csv or excel file
    raw : bool
        Show raw data
    sheet_name: str
        Optionally specify the name of the sheet the data is exported to.
    external_axes : bool, optional
        Whether to return the figure object or not, by default False
    """
    ...

@log_start_end(log=logger)
@check_api_key(["API_FRED_KEY"])
def plot_dwpcr(parameter: str = ..., start_date: Optional[str] = ..., end_date: Optional[str] = ..., export: str = ..., sheet_name: str = ..., external_axes: bool = ...): # -> OpenBBFigure | None:
    """Plot Discount Window Primary Credit Rate.

    Parameters
    ----------
    parameter: str
        FRED ID of DWPCR data to plot, options: ['MPCREDIT', 'RIFSRPF02ND', 'WPCREDIT', 'DPCREDIT', 'RIFSRPF02NA']
    start_date: Optional[str]
        Start date, formatted YYYY-MM-DD
    end_date: Optional[str]
        End date, formatted YYYY-MM-DD
    export: str
        Export data to csv or excel file
    external_axes : bool, optional
        Whether to return the figure object or not, by default False
    """
    ...

@log_start_end(log=logger)
@check_api_key(["API_FRED_KEY"])
def plot_ecb(start_date: Optional[str] = ..., end_date: Optional[str] = ..., interest_type: Optional[str] = ..., raw: bool = ..., export: str = ..., sheet_name: str = ..., external_axes: bool = ..., limit: int = ...): # -> OpenBBFigure | None:
    """Plot the key ECB interest rates.

    The Governing Council of the ECB sets the key interest rates for the euro area:

    - The interest rate on the main refinancing operations (MRO), which provide
    the bulk of liquidity to the banking system.
    - The rate on the deposit facility, which banks may use to make overnight deposits with the Eurosystem.
    - The rate on the marginal lending facility, which offers overnight credit to banks from the Eurosystem.

    Parameters
    ----------
    start_date: Optional[str]
        Start date, formatted YYYY-MM-DD
    end_date: Optional[str]
        End date, formatted YYYY-MM-DD
    interest_type: Optional[str]
        The ability to decide what interest rate to plot
    export: str
        Export data to csv or excel file
    external_axes : bool, optional
        Whether to return the figure object or not, by default False
    """
    ...

@log_start_end(log=logger)
@check_api_key(["API_FRED_KEY"])
def plot_tmc(parameter: str = ..., start_date: Optional[str] = ..., end_date: Optional[str] = ..., export: str = ..., sheet_name: str = ..., external_axes: bool = ...): # -> OpenBBFigure | None:
    """Plot 10-Year Treasury Constant Maturity Minus Selected Treasury Constant Maturity data.

    Constant maturity is the theoretical value of a U.S. Treasury that is based on recent values of auctioned U.S.
    Treasuries. The value is obtained by the U.S. Treasury on a daily basis through interpolation of the Treasury
    yield curve which, in turn, is based on closing bid-yields of actively-traded Treasury securities.

    Parameters
    ----------
    parameter: str
        FRED ID of TMC data to plot, options: ['T10Y3M', 'T10Y3M']
    start_date: Optional[str]
        Start date, formatted YYYY-MM-DD
    end_date: Optional[str]
        End date, formatted YYYY-MM-DD
    export: str
        Export data to csv or excel file
    external_axes : bool, optional
        Whether to return the figure object or not, by default False
    """
    ...

@log_start_end(log=logger)
@check_api_key(["API_FRED_KEY"])
def plot_ffrmc(parameter: str = ..., start_date: Optional[str] = ..., end_date: Optional[str] = ..., export: str = ..., sheet_name: str = ..., external_axes: bool = ...): # -> OpenBBFigure | None:
    """Plot Selected Treasury Constant Maturity Minus Federal Funds Rate data.

    Constant maturity is the theoretical value of a U.S. Treasury that is based on recent values of auctioned U.S.
    Treasuries. The value is obtained by the U.S. Treasury on a daily basis through interpolation of the Treasury
    yield curve which, in turn, is based on closing bid-yields of actively-traded Treasury securities.

    Parameters
    ----------
    parameter: str
        FRED ID of FFRMC data to plot
    start_date: Optional[str]
        Start date, formatted YYYY-MM-DD
    end_date: Optional[str]
        End date, formatted YYYY-MM-DD
    export: str
        Export data to csv or excel file
    external_axes : bool, optional
        Whether to return the figure object or not, by default False
    """
    ...

@log_start_end(log=logger)
@check_api_key(["API_FRED_KEY"])
def display_yield_curve(date: str = ..., inflation_adjusted: bool = ..., raw: bool = ..., export: str = ..., sheet_name: str = ..., external_axes: bool = ...): # -> OpenBBFigure | None:
    """Display yield curve based on US Treasury rates for a specified date.

    The graphic depiction of the relationship between the yield on bonds of the same credit quality but different
    maturities is known as the yield curve. In the past, most market participants have constructed yield curves from
    the observations of prices and yields in the Treasury market. Two reasons account for this tendency. First,
    Treasury securities are viewed as free of default risk, and differences in creditworthiness do not affect yield
    estimates. Second, as the most active bond market, the Treasury market offers the fewest problems of illiquidity
    or infrequent trading. The key function of the Treasury yield curve is to serve as a benchmark for pricing bonds
    and setting yields in other sectors of the debt market.

    It is clear that the market’s expectations of future rate changes are one important determinant of the
    yield-curve shape. For example, a steeply upward-sloping curve may indicate market expectations of near-term Fed
    tightening or of rising inflation. However, it may be too restrictive to assume that the yield differences across
    bonds with different maturities only reflect the market’s rate expectations. The well-known pure expectations
    hypothesis has such an extreme implication. The pure expectations hypothesis asserts that all government bonds
    have the same near-term expected return (as the nominally riskless short-term bond) because the return-seeking
    activity of risk-neutral traders removes all expected return differentials across bonds.

    Parameters
    ----------
    date: str
        Date to get curve for. If None, gets most recent date (format yyyy-mm-dd)
    external_axes : bool, optional
        Whether to return the figure object or not, by default False
    raw : bool
        Output only raw data
    export : str
        Export data to csv,json,xlsx or png,jpg,pdf,svg file
    """
    ...

@log_start_end(log=logger)
@check_api_key(["API_FRED_KEY"])
def plot_usrates(parameter: str = ..., maturity: str = ..., start_date: Optional[str] = ..., end_date: Optional[str] = ..., raw: bool = ..., export: str = ..., sheet_name: str = ..., external_axes: bool = ..., limit: int = ...): # -> OpenBBFigure | None:
    """Plot various treasury rates from the United States

    A Treasury Bill (T-Bill) is a short-term U.S. government debt obligation backed by the Treasury Department with a
    maturity of one year or less. Treasury bills are usually sold in denominations of $1,000. However, some can reach
    a maximum denomination of $5 million in non-competitive bids. These securities are widely regarded as low-risk
    and secure investments.

    Yields on Treasury nominal securities at “constant maturity” are interpolated by the U.S. Treasury from the daily
    yield curve for non-inflation-indexed Treasury securities. This curve, which relates the yield on a security to
    its time to maturity, is based on the closing market bid yields on actively traded Treasury securities in the
    over-the-counter market. These market yields are calculated from composites of quotations obtained by the Federal
    Reserve Bank of New York. The constant maturity yield values are read from the yield curve at fixed maturities,
    currently 1, 3, and 6 months and 1, 2, 3, 5, 7, 10, 20, and 30 years. This method provides a yield for a 10-year
    maturity, for example, even if no outstanding security has exactly 10 years remaining to maturity. Similarly,
    yields on inflation-indexed securities at “constant maturity” are interpolated from the daily yield curve for
    Treasury inflation protected securities in the over-the-counter market. The inflation-indexed constant maturity
    yields are read from this yield curve at fixed maturities, currently 5, 7, 10, 20, and 30 years.

    Parameters
    ----------
    parameter: str
        Either "tbills", "cmn", or "tips".
    maturity: str
        Depending on the chosen parameter, a set of maturities is available.
    series_id: str
        FRED ID of Treasury Bill Secondary Market Rate data to plot, options: ['TB3MS', 'DTB4WK', 'DTB1YR', 'DTB6']
    start_date: Optional[str]
        Start date, formatted YYYY-MM-DD
    end_date: Optional[str]
        End date, formatted YYYY-MM-DD
    export: str
        Export data to csv or excel file
    external_axes : bool, optional
        Whether to return the figure object or not, by default False
    """
    ...

@log_start_end(log=logger)
@check_api_key(["API_FRED_KEY"])
def plot_tbffr(parameter: str = ..., start_date: Optional[str] = ..., end_date: Optional[str] = ..., export: str = ..., sheet_name: str = ..., external_axes: bool = ...): # -> OpenBBFigure | None:
    """Plot Selected Treasury Bill Minus Federal Funds Rate data.

    Parameters
    ----------
    parameter: str
        FRED ID of TBFFR data to plot, options: ['TB3SMFFM', 'TB6SMFFM']
    start_date: Optional[str]
        Start date, formatted YYYY-MM-DD
    end_date: Optional[str]
        End date, formatted YYYY-MM-DD
    export: str
        Export data to csv or excel file
    external_axes : bool, optional
        Whether to return the figure object or not, by default False
    """
    ...

@log_start_end(log=logger)
@check_api_key(["API_FRED_KEY"])
def plot_icebofa(data_type: str = ..., category: str = ..., area: str = ..., grade: str = ..., options: bool = ..., description: bool = ..., start_date: Optional[str] = ..., end_date: Optional[str] = ..., raw: bool = ..., export: str = ..., sheet_name: str = ..., external_axes: bool = ..., limit: int = ...): # -> OpenBBFigure | None:
    """Plot ICE BofA US Corporate Bond Index data.

    Parameters
    ----------
    data_type: str
        The type of data you want to see, either "yield", "yield_to_worst", "total_return", or "spread"
    category: str
        The type of category you want to see, either "all", "duration", "eur" or "usd".
    area: str
        The type of area you want to see, either "asia", "emea", "eu", "ex_g10", "latin_america" or "us"
    grade: str
        The type of grade you want to see, either "a", "aa", "aaa", "b", "bb", "bbb", "ccc", "crossover",
        "high_grade", "high_yield", "non_financial", "non_sovereign", "private_sector", "public_sector"
    start_date: Optional[str]
        Start date, formatted YYYY-MM-DD
    end_date: Optional[str]
        End date, formatted YYYY-MM-DD
    raw: bool
        Show raw data
    export: str
        Export data to csv or excel file
    sheet_name: str
        Name of the sheet to export to
    external_axes : bool, optional
        Whether to return the figure object or not, by default False
    """
    ...

@log_start_end(log=logger)
@check_api_key(["API_FRED_KEY"])
def plot_moody(data_type: str = ..., spread: Optional[str] = ..., start_date: Optional[str] = ..., end_date: Optional[str] = ..., raw: bool = ..., export: str = ..., sheet_name: str = ..., external_axes: bool = ..., limit: int = ...): # -> OpenBBFigure | None:
    """Plot Moody Corporate Bond Index data
    Parameters
    ----------
    data_type: str
        The type of data you want to see, either "aaa" or "baa"
    spread: Optional[str]
        Whether you want to show the spread for treasury or fed_funds
    start_date: Optional[str]
        Start date, formatted YYYY-MM-DD
    end_date: Optional[str]
        End date, formatted YYYY-MM-DD
    raw: bool
        Show raw data
    export: str
        Export data to csv or excel file
    sheet_name: str
        Name of the sheet to export to
    external_axes : bool, optional
        Whether to return the figure object or not, by default False
    """
    ...

@log_start_end(log=logger)
@check_api_key(["API_FRED_KEY"])
def plot_cp(maturity: str = ..., category: str = ..., grade: str = ..., options: bool = ..., description: bool = ..., start_date: Optional[str] = ..., end_date: Optional[str] = ..., raw: bool = ..., export: str = ..., sheet_name: str = ..., external_axes: bool = ..., limit: int = ...): # -> OpenBBFigure | None:
    """Plot Commercial Paper

    Parameters
    ----------
    maturity: str
        The maturity you want to see, either "overnight", "7d", "15d", "30d", "60d" or "90d"
    category: str
        The category you want to see, either "asset_backed", "financial" or "non_financial"
    grade: str
        The type of grade you want to see, either "a2_p2" or "aa"
    description: bool
        Whether you wish to obtain a description of the data.
    start_date: Optional[str]
        Start date, formatted YYYY-MM-DD
    end_date: Optional[str]
        End date, formatted YYYY-MM-DD
    raw: bool
        Show raw data
    export: str
        Export data to csv or excel file
    sheet_name: str
        Name of the sheet to export to
    external_axes : bool, optional
        Whether to return the figure object or not, by default False
    """
    ...

@log_start_end(log=logger)
@check_api_key(["API_FRED_KEY"])
def plot_spot(maturity: List = ..., category: List = ..., description: bool = ..., start_date: Optional[str] = ..., end_date: Optional[str] = ..., raw: bool = ..., export: str = ..., sheet_name: str = ..., external_axes: bool = ..., limit: int = ...): # -> OpenBBFigure | None:
    """Plot Spot Rates for a given maturity

    The spot rate for any maturity is the yield on a bond that provides
    a single payment at that maturity. This is a zero coupon bond. Because each
    spot rate pertains to a single cashflow, it is the relevant interest rate
    concept for discounting a pension liability at the same maturity.

    Parameters
    ----------
    maturity: str
        The maturity you want to see (ranging from '1y' to '100y')
    category: list
        The category you want to see ('par_yield' and/or 'spot_rate')
    description: bool
        Whether you wish to obtain a description of the data.
    start_date: Optional[str]
        Start date, formatted YYYY-MM-DD
    end_date: Optional[str]
        End date, formatted YYYY-MM-DD
    raw: bool
        Show raw data
    export: str
        Export data to csv or excel file
    sheet_name: str
        Name of the sheet to export to
    external_axes : bool, optional
        Whether to return the figure object or not, by default False
    """
    ...

@log_start_end(log=logger)
@check_api_key(["API_FRED_KEY"])
def plot_hqm(date: Optional[str] = ..., par: bool = ..., raw: bool = ..., export: str = ..., sheet_name: str = ..., external_axes: bool = ...): # -> OpenBBFigure | None:
    """Plot the HQM yield curve

    The HQM yield curve represents the high quality corporate bond market, i.e.,
    corporate bonds rated AAA, AA, or A.  The HQM curve contains two regression terms. These
    terms are adjustment factors that blend AAA, AA, and A bonds into a single HQM yield curve
    that is the market-weighted average (MWA) quality of high quality bonds.

    Parameters
    ----------
    date: str
        The date of the yield curve you wish to plot
    par: bool
        Whether you wish to plot the par yield curve as well
    raw: bool
        Show raw data
    export: str
        Export data to csv or excel file
    sheet_name: str
        Name of the sheet to export to
    external_axes : bool, optional
        Whether to return the figure object or not, by default False
    """
    ...

