"""
This type stub file was generated by pyright.
"""

import pandas as pd
from datetime import datetime
from typing import List
from openbb_terminal.decorators import check_api_key, log_start_end

logger = ...
def load_stock_intrinio(symbol: str, start_date: datetime, end_date: datetime, weekly: bool = ..., monthly: bool = ...) -> pd.DataFrame:
    ...

def load_stock_av(symbol: str, interval: str, start_date: datetime, end_date: datetime, interval_min: str = ...) -> pd.DataFrame:
    ...

def load_stock_yf(symbol: str, start_date: datetime, end_date: datetime, weekly: bool, monthly: bool) -> pd.DataFrame:
    ...

def load_stock_eodhd(symbol: str, start_date: datetime, end_date: datetime, weekly: bool, monthly: bool, intraday: bool = ...) -> pd.DataFrame:
    ...

@check_api_key(["API_POLYGON_KEY"])
def load_stock_polygon(symbol: str, start_date: datetime, end_date: datetime, weekly: bool, monthly: bool) -> pd.DataFrame:
    ...

@log_start_end(log=logger)
@check_api_key(["API_KEY_FINANCIALMODELINGPREP"])
def get_quote(symbols: List[str]) -> pd.DataFrame:
    """Gets ticker quote from FMP

    Parameters
    ----------
    symbols : List[str]
        A list of Stock ticker symbols

    Returns
    -------
    pd.DataFrame
        Dataframe of ticker quote

    Examples
    --------

    A single ticker must be entered as a list.

    >>> df = openbb.stocks.quote(["AAPL"])

    Multiple tickers can be retrieved.

    >>> df = openbb.stocks.quote(["AAPL","MSFT","GOOG","NFLX","META","AMZN","NVDA"])
    """
    ...

