"""
This type stub file was generated by pyright.
"""

from typing import Optional
from openbb_terminal.decorators import log_start_end

"""Fdscanner view"""
__docformat__ = ...
logger = ...
@log_start_end(log=logger)
def display_options(limit: int = ..., sortby: str = ..., ascend: bool = ..., calls_only: bool = ..., puts_only: bool = ..., export: str = ..., sheet_name: Optional[str] = ...): # -> None:
    """Displays the unusual options table

    Parameters
    ----------
    limit: int
        Number of rows to show
    sortby: str
        Data column to sort on
    ascend: bool
        Whether to sort in ascend order
    calls_only : bool
        Flag to only show calls
    puts_only : bool
        Flag to show puts only
    sheet_name: str
        Optionally specify the name of the sheet the data is exported to.
    export: str
        File type to export
    """
    ...

