"""
This type stub file was generated by pyright.
"""

import pandas as pd
from typing import List, Tuple, Union
from darts import TimeSeries
from openbb_terminal.decorators import log_start_end

"""Quantile Anomaly Detection Model"""
__docformat__ = ...
logger = ...
@log_start_end(log=logger)
def get_anomaly_detection_data(data: Union[pd.Series, pd.DataFrame], target_column: str = ..., train_split: float = ...) -> Tuple[TimeSeries, List[TimeSeries], List[TimeSeries]]:
    """Get Quantile Anomaly Detection Data

    Parameters
    ----------
    data: Union[pd.Series, pd.DataFrame]

    Input Data
    -------
    target_column: str
        Target column to forecast. Defaults to "close".
    train_split: (float, optional)
        Train/val split. Defaults to 0.85.

    Returns
    -------
    Tuple[
        List[TimeSeries],
        List[TimeSeries],
        List[TimeSeries],
        ]
    """
    ...

