"""
This type stub file was generated by pyright.
"""

import pandas as pd
from datetime import datetime
from typing import Optional, Union
from openbb_terminal.decorators import log_start_end

"""RNN View"""
__docformat__ = ...
logger = ...
@log_start_end(log=logger)
def display_rnn_forecast(data: Union[pd.DataFrame, pd.Series], target_column: str = ..., dataset_name: str = ..., n_predict: int = ..., train_split: float = ..., forecast_horizon: int = ..., model_type: str = ..., hidden_dim: int = ..., dropout: float = ..., batch_size: int = ..., n_epochs: int = ..., learning_rate: float = ..., model_save_name: str = ..., training_length: int = ..., input_chunk_size: int = ..., force_reset: bool = ..., save_checkpoints: bool = ..., export: str = ..., sheet_name: Optional[str] = ..., residuals: bool = ..., forecast_only: bool = ..., start_date: Optional[datetime] = ..., end_date: Optional[datetime] = ..., naive: bool = ..., export_pred_raw: bool = ..., metric: str = ..., external_axes: bool = ...): # -> OpenBBFigure | None:
    """Display RNN forecast

    Parameters
    ----------
    data: Union[pd.Series, pd.DataFrame]
        Input Data
    dataset_name: str
        The name of the ticker to be predicted
    n_predict: int
        Days to predict. Defaults to 5.
    target_column: str
        Target column to forecast. Defaults to "close".
    train_split: float
        Train/val split. Defaults to 0.85.
    forecast_horizon: int
        Forecast horizon when performing historical forecasting. Defaults to 5.
    model_type: str
        Either a string specifying the RNN module type ("RNN", "LSTM" or "GRU"). Defaults to "LSTM".
    hidden_dim: int
        Size for feature maps for each hidden RNN layer.. Defaults to 20.
    dropout: float
        Fraction of neurons affected by Dropout. Defaults to 0.0.
    batch_size: int
        Number of time series (input and output sequences) used in each training pass. Defaults to 32.
    n_epochs: int
        Number of epochs over which to train the model. Defaults to 100.
    learning_rate: float
        Defaults to 1e-3.
    model_save_name: str
        Name for model. Defaults to "brnn_model".
    force_reset: bool
        If set to True, any previously-existing model with the same name will be reset
        (all checkpoints will be discarded). Defaults to True.
    save_checkpoints: bool
        Whether or not to automatically save the untrained model and checkpoints from training. Defaults to True.
    forecast_only: bool
        Whether to only show dates in the forecasting range. Defaults to False.
    sheet_name: str
        Optionally specify the name of the sheet the data is exported to.
    export: str
        Format to export data
    residuals: bool
        Whether to show residuals for the model. Defaults to False.
    start_date: Optional[datetime]
        The starting date to perform analysis, data before this is trimmed. Defaults to None.
    end_date: Optional[datetime]
        The ending date to perform analysis, data after this is trimmed. Defaults to None.
    naive: bool
        Whether to show the naive baseline. This just assumes the closing price will be the same
        as the previous day's closing price. Defaults to False.
    export_pred_raw: bool
        Whether to export the raw predictions. Defaults to False.
    metric: str
        The metric to use for the forecast. Defaults to "mape".
    external_axes : bool, optional
        Whether to return the figure object or not, by default False
    """
    ...

