"""
This type stub file was generated by pyright.
"""

import pandas as pd
from typing import List, Optional, Tuple, Union
from darts import TimeSeries
from darts.models import TCNModel
from openbb_terminal.decorators import log_start_end

"""TCN Model"""
__docformat__ = ...
logger = ...
@log_start_end(log=logger)
def get_tcn_data(data: Union[pd.Series, pd.DataFrame], target_column: str = ..., n_predict: int = ..., past_covariates: Optional[str] = ..., train_split: float = ..., forecast_horizon: int = ..., input_chunk_length: int = ..., output_chunk_length: int = ..., dropout: float = ..., num_filters: int = ..., weight_norm: bool = ..., dilation_base: int = ..., n_epochs: int = ..., learning_rate: float = ..., batch_size: int = ..., model_save_name: str = ..., force_reset: bool = ..., save_checkpoints: bool = ..., metric: str = ...) -> Tuple[List[Optional[TimeSeries]], List[Optional[TimeSeries]], List[Optional[TimeSeries]], Optional[float], Optional[type[TCNModel]],]:
    """Perform TCN forecasting

    Parameters
    ----------
    data: Union[pd.Series, pd.DataFrame]
        Input Data
    target_column: str
        Target column to forecast. Defaults to "close".
    n_predict: int
        Days to predict. Defaults to 5.
    train_split: float
        Train/val split. Defaults to 0.85.
    past_covariates: str
        Multiple secondary columns to factor in when forecasting. Defaults to None.
    forecast_horizon: int
        Forecast horizon when performing historical forecasting. Defaults to 5.
    input_chunk_length: int
        Number of past time steps that are fed to the forecasting module at prediction time. Defaults to 14.
    output_chunk_length: int
        The length of the forecast of the model. Defaults to 5.
    dropout: float
        Fraction of neurons affected by Dropout. Defaults to 0.1.
    num_filters: int
        The number of filters in a convolutional layer of the TCN. Defaults to 6.
    weight_norm: bool
        Boolean value indicating whether to use weight normalization. Defaults to True.
    dilation_base: int
        The base of the exponent that will determine the dilation on every level. Defaults to 2.
    batch_size: int
        Number of time series (input and output sequences) used in each training pass. Defaults to 32.
    n_epochs: int
        Number of epochs over which to train the model. Defaults to 100.
    learning_rate: float
        Defaults to 1e-3.
    model_save_name: str
        Name for model. Defaults to "brnn_model".
    force_reset: bool
        If set to True, any previously-existing model with the same name will be reset
        (all checkpoints will be discarded). Defaults to True.
    save_checkpoints: bool
        Whether or not to automatically save the untrained model and checkpoints from training.
        Defaults to True.
    metric: str
        Metric to use for model selection. Defaults to "mape".

    Returns
    -------
    Tuple[List[TimeSeries], List[TimeSeries], List[TimeSeries], Optional[float], type[TCNModel]]
        Adjusted Data series,
        Historical forecast by best RNN model,
        list of Predictions,
        Mean average precision error,
        Best TCN Model.
    """
    ...

