"""
This type stub file was generated by pyright.
"""

from typing import Iterator, TextIO

def str2bool(string): # -> bool:
    ...

def format_timestamp(seconds: float, always_include_hours: bool = ..., decimal_marker: str = ...): # -> str:
    ...

def break_line(line: str, length: int): # -> str:
    ...

def process_segment(segment: dict, line_length: int = ...): # -> dict[Unknown, Unknown]:
    ...

def write_vtt(transcript: Iterator[dict], file: TextIO, line_length: int = ...): # -> None:
    ...

def write_srt(transcript: Iterator[dict], file: TextIO, line_length: int = ...): # -> None:
    ...

def slugify(title): # -> LiteralString:
    ...

