"""
This type stub file was generated by pyright.
"""

from typing import List
from langchain.chains.base import Chain
from langchain_experimental.plan_and_execute.executors.base import BaseExecutor
from langchain_experimental.plan_and_execute.planners.base import BasePlanner
from langchain_experimental.plan_and_execute.schema import BaseStepContainer

class PlanAndExecute(Chain):
    """Plan and execute a chain of steps."""
    planner: BasePlanner
    executor: BaseExecutor
    step_container: BaseStepContainer = ...
    input_key: str = ...
    output_key: str = ...
    @property
    def input_keys(self) -> List[str]:
        ...
    
    @property
    def output_keys(self) -> List[str]:
        ...
    


