"""
This type stub file was generated by pyright.
"""

from typing import List, Optional
from openbb_terminal.decorators import log_start_end
from openbb_terminal.parent_classes import BaseController

"""Tools Controller Module"""
__docformat__ = ...
logger = ...
class ToolsController(BaseController):
    """Tools Controller class"""
    CHOICES_COMMANDS = ...
    PATH = ...
    CHOICES_GENERATION = ...
    def __init__(self, queue: Optional[List[str]] = ...) -> None:
        """Constructor"""
        ...
    
    def print_help(self): # -> None:
        """Print help"""
        ...
    
    @log_start_end(log=logger)
    def call_il(self, other_args: List[str]): # -> None:
        """Process il command"""
        ...
    
    @log_start_end(log=logger)
    def call_aprtoapy(self, other_args: List[str]): # -> None:
        """Process aprtoapy command"""
        ...
    


