"""
This type stub file was generated by pyright.
"""

def change_variation(change: float) -> float:
    """Helper to convert change variation

    Parameters
    ----------
    change: float
        percentage change

    Returns
    -------
    float:
        converted value
    """
    ...

def calculate_hold_value(changeA: float, changeB: float, proportion: float) -> float:
    """Calculates hold value of two different coins

    Parameters
    ----------
    changeA: float
        price change of crypto A in percentage
    changeB: float
        price change of crypto B in percentage
    proportion: float
        percentage of first token in pool

    Returns
    -------
    float:
        hold value
    """
    ...

def calculate_pool_value(changeA, changeB, proportion):
    """Calculates pool value of two different coins

    Parameters
    ----------
    changeA: float
        price change of crypto A in percentage
    changeB: float
        price change of crypto B in percentage
    proportion: float
        percentage of first token in pool

    Returns
    -------
    float:
        pool value
    """
    ...

