"""
This type stub file was generated by pyright.
"""

import pandas as pd
from typing import Tuple
from openbb_terminal.decorators import log_start_end

"""Tools Model"""
__docformat__ = ...
logger = ...
@log_start_end(log=logger)
def calculate_apy(apr: float, compounding_times: int) -> Tuple[pd.DataFrame, str]:
    """Converts apr into apy

    Parameters
    ----------
    apr: float
        value in percentage
    compounding_times: int
        number of compounded periods in a year

    Returns
    -------
    Tuple[pd.DataFrame, str]
        - pd.DataFrame: dataframe with results
        - str: narrative version of results
    """
    ...

@log_start_end(log=logger)
def calculate_il(price_changeA: float, price_changeB: float, proportion: float, initial_pool_value: float) -> Tuple[pd.DataFrame, str]:
    """Calculates Impermanent Loss in a custom liquidity pool

    Parameters
    ----------
    price_changeA: float
        price change of crypto A in percentage
    price_changeB: float
        price change of crypto B in percentage
    proportion: float
        percentage of first token in pool
    initial_pool_value: float
        initial value that pool contains

    Returns
    -------
    Tuple[pd.DataFrame, str]
        - pd.DataFrame: dataframe with results
        - str: narrative version of results
    """
    ...

