"""
This type stub file was generated by pyright.
"""

from pandas.core.frame import DataFrame
from openbb_terminal.decorators import log_start_end

""" ARK Model """
__docformat__ = ...
logger = ...
@log_start_end(log=logger)
def get_ark_orders(buys_only: bool = ..., sells_only: bool = ..., fund: str = ...) -> DataFrame:
    """Returns ARK orders in a Dataframe

    Parameters
    ----------
    buys_only: bool
        Flag to filter on buys only
    sells_only: bool
        Flag to sort on sells only
    fund: str
        Optional filter by fund

    Returns
    -------
    DataFrame
        ARK orders data frame with the following columns -
        (ticker, date, shares, weight, fund, direction)
    """
    ...

@log_start_end(log=logger)
def add_order_total(data: DataFrame) -> DataFrame:
    """Takes an ARK orders dataframe and pulls data from Yahoo Finance to add
    volume, open, close, high, low, and total columns

    Parameters
    ----------
    data: DataFrame
        ARK orders data frame with the following columns -
        (ticker, date, shares, weight, fund, direction)

    Returns
    -------
    DataFrame
        ARK orders data frame with the following columns -
        (ticker, date, shares, volume, open, close, high, low, total, weight, fund, direction)
    """
    ...

