"""
This type stub file was generated by pyright.
"""

from typing import Optional
from openbb_terminal.decorators import check_api_key, log_start_end

logger = ...
@log_start_end(log=logger)
@check_api_key(["API_FINNHUB_KEY"])
def past_ipo(num_days_behind: int = ..., start_date: Optional[str] = ..., limit: int = ..., export: str = ..., sheet_name: Optional[str] = ...): # -> None:
    """Past IPOs dates. [Source: Finnhub]

    Parameters
    ----------
    num_days_behind: int
        Number of days to look behind for IPOs dates
    start_date: str
        The starting date (format YYYY-MM-DD) to look for IPOs
    limit: int
        Limit number of IPOs to display. Default is 20
    export : str
        Export dataframe data to csv,json,xlsx file
    """
    ...

@log_start_end(log=logger)
@check_api_key(["API_FINNHUB_KEY"])
def future_ipo(num_days_ahead: int = ..., end_date: Optional[str] = ..., limit: int = ..., export: str = ..., sheet_name: Optional[str] = ...): # -> None:
    """Future IPOs dates. [Source: Finnhub]

    Parameters
    ----------
    num_days_ahead: int
        Number of days to look ahead for IPOs dates
    end_date: datetime
        The end date (format YYYY-MM-DD) to look for IPOs from today onwards
    limit: int
        Limit number of IPOs to display. Default is 20
    export : str
        Export dataframe data to csv,json,xlsx file
    """
    ...

