"""
This type stub file was generated by pyright.
"""

from datetime import date
from pandas.core.frame import DataFrame
from openbb_terminal.decorators import log_start_end

""" Seeking Alpha Model """
__docformat__ = ...
logger = ...
@log_start_end(log=logger)
def get_earnings_html(url_next_earnings: str) -> str:
    """Wraps HTTP request for testibility

    Parameters
    ----------
    url_next_earnings : str
        Next earnings URL

    Returns
    -------
    str
        HTML page of next earnings
    """
    ...

def get_filters(date_str: str) -> str:
    ...

@log_start_end(log=logger)
def get_next_earnings(limit: int = ..., start_date: date = ...) -> DataFrame:
    """Returns a DataFrame with upcoming earnings

    Parameters
    ----------
    limit : int
        Number of days to look ahead
    start_date: date
        Date to start from. Defaults to today

    Returns
    -------
    DataFrame
        Upcoming earnings DataFrame
    """
    ...

@log_start_end(log=logger)
def get_articles_html(url_articles: str) -> str:
    """Wraps HTTP request for testability

    Parameters
    ----------
    url_articles : str
        Articles URL

    Returns
    -------
    str
        HTML page of articles
    """
    ...

@log_start_end(log=logger)
def get_trending_list(limit: int = ...) -> list:
    """Returns a list of trending articles

    Parameters
    ----------
    limit: int
        Number of articles

    Returns
    -------
    list
        Trending articles list
    """
    ...

@log_start_end(log=logger)
def get_article_data(article_id: int) -> dict:
    """Returns an article

    Parameters
    ----------
    article_id : int
        Article ID

    Returns
    -------
    dict
        Article data
    """
    ...

@log_start_end(log=logger)
def get_news_html(news_type: str = ...) -> dict:
    """Gets news. [Source: SeekingAlpha]

    Parameters
    ----------
    news_type : str
        From: Top-News, On-The-Move, Market-Pulse, Notable-Calls, Buybacks, Commodities, Crypto, Issuance, Global,
        Guidance, IPOs, SPACs, Politics, M-A, Consumer, Energy, Financials, Healthcare, MLPs, REITs, Technology

    Returns
    -------
    dict
        HTML page of articles
    """
    ...

