"""
This type stub file was generated by pyright.
"""

from typing import Any, List, Literal, Optional

console = ...
menus = Literal["", "featflags", "settings"]
openbb_posthog = ...
def handle_error(name: str, default: Any, menu: menus = ...): # -> Any:
    """Handles the error by returning the default value and printing an
    informative error message.

    Parameters
    ----------
    name: str
        The name of the environment variable
    default: Any
        The value to return if the converter fails
    menu: menus
        If provided, will tell the user where to fix the setting

    Returns
    ----------
    Any
        The default value

    """
    ...

def strtobool(val): # -> bool:
    """Convert a string representation of truth to true (1) or false (0).

    True values are 'y', 'yes', 't', 'true', 'on', and '1'; false values
    are 'n', 'no', 'f', 'false', 'off', and '0'.  Raises ValueError if
    'val' is anything else.
    """
    ...

def load_env_files(): # -> None:
    """
    Loads the dotenv files in the following order:
    1. Repository .env file
    2. Package .env file
    3. User .env file

    This allows the user to override the package settings with their own
    settings, and the package to override the repository settings.

    openbb_terminal modules are reloaded to refresh config files with new env,
    otherwise they will use cache with old variables.
    """
    ...

def remove_log_handlers(): # -> None:
    """Remove the log handlers - needs to be done before reloading modules."""
    ...

def clear_openbb_env_vars(exceptions: Optional[List[str]] = ...): # -> None:
    """Clear openbb environment variables."""
    ...

