"""
This type stub file was generated by pyright.
"""

from typing import List, Optional
from openbb_terminal.decorators import log_start_end
from openbb_terminal.parent_classes import BaseController

"""Sources Controller Module"""
__docformat__ = ...
logger = ...
class SourcesController(BaseController):
    """Sources Controller class"""
    CHOICES_COMMANDS: List[str] = ...
    PATH = ...
    CHOICES_GENERATION = ...
    def __init__(self, queue: Optional[List[str]] = ...) -> None:
        """Constructor"""
        ...
    
    def update_print_help(self): # -> None:
        """Update print help"""
        ...
    
    def parse_input(self, an_input: str) -> List:
        """Parse controller input

        Overrides the parent class function to handle github org/repo path convention.
        See `BaseController.parse_input()` for details.
        """
        ...
    
    def print_help(self): # -> None:
        """Print help"""
        ...
    
    @log_start_end(log=logger)
    def call_get(self, other_args): # -> None:
        """Process get command"""
        ...
    
    @log_start_end(log=logger)
    def call_set(self, other_args): # -> None:
        """Process set command"""
        ...
    


