"""
This type stub file was generated by pyright.
"""

import pandas as pd
from typing import Any, Dict, Optional, Tuple
from openbb_terminal.decorators import log_start_end

"""Topledger model"""
__docformat__ = ...
logger = ...
MAPPING: Dict[str, Any] = ...
@log_start_end(log=logger)
def make_request(org_slug=..., query_slug=...) -> Tuple[Optional[int], Any]:
    """Helper methods for requests to topledger's query results [Source: Topledger]

    Parameters
    ----------
    org_slug: str
        Organization Slug
    query_slug: str
        Query Slug

    Returns
    -------
    Tuple[Optional[int], Any]
        status code, response from api request
    """
    ...

@log_start_end(log=logger)
def get_topledger_data(org_slug: str, query_slug: str) -> pd.DataFrame:
    """Returns Topledger's Data for the given Organization's Slug[org_slug] based
    on Query Slug[query_slug] [Source: Topledger]

    Parameters
    ----------
    org_slug: str
        Organization Slug
    query_slug: str
        Query Slug

    Returns
    -------
    pd.DataFrame
        Topledger Data
    """
    ...

