"""
This type stub file was generated by pyright.
"""

from typing import Optional
from openbb_terminal.decorators import check_api_key, log_start_end

"""Cryptopanic view"""
__docformat__ = ...
logger = ...
@log_start_end(log=logger)
@check_api_key(["API_CRYPTO_PANIC_KEY"])
def display_news(post_kind: str = ..., region: str = ..., filter_: Optional[str] = ..., source: Optional[str] = ..., symbol: Optional[str] = ..., limit: int = ..., ascend: bool = ..., export: str = ..., sheet_name: Optional[str] = ...) -> None:
    """Prints table showing recent posts from CryptoPanic news aggregator platform.
    [Source: https://cryptopanic.com/]

    Parameters
    ----------
    limit: int
        number of news to display
    post_kind: str
        Filter by category of news. Available values: news or media.
    filter_: Optional[str]
        Filter by kind of news. One from list: rising|hot|bullish|bearish|important|saved|lol
    region: str
        Filter news by regions. Available regions are: en (English), de (Deutsch), nl (Dutch),
        es (Español), fr (Français), it (Italiano), pt (Português), ru (Русский)
    ascend: bool
        Sort in ascending order.
    export : str
        Export dataframe data to csv,json,xlsx file
    """
    ...

