"""
This type stub file was generated by pyright.
"""

from typing import List, Optional
from openbb_terminal.decorators import log_start_end
from openbb_terminal.parent_classes import BaseController

"""Coinbase Controller"""
__docformat__ = ...
logger = ...
class CoinbaseController(BaseController):
    """Coinbase Controller class"""
    CHOICES_COMMANDS = ...
    order_sortby = ...
    deposit_sort = ...
    deposit_type = ...
    PATH = ...
    CHOICES_GENERATION = ...
    def __init__(self, queue: Optional[List[str]] = ...) -> None:
        """Constructor"""
        ...
    
    def print_help(self): # -> None:
        """Print help"""
        ...
    
    @log_start_end(log=logger)
    def call_account(self, other_args): # -> None:
        """Process account command"""
        ...
    
    @log_start_end(log=logger)
    def call_history(self, other_args): # -> None:
        """Process account command"""
        ...
    
    @log_start_end(log=logger)
    def call_orders(self, other_args): # -> None:
        """Process orders command"""
        ...
    
    @log_start_end(log=logger)
    def call_deposits(self, other_args): # -> None:
        """Process deposits command"""
        ...
    


