"""
This type stub file was generated by pyright.
"""

import pandas as pd

def clean_df(df: pd.DataFrame) -> pd.DataFrame:
    """
    Cleans the dataframe before displaying it.

    Parameters
    ----------
    df : pd.DataFrame
        The dataframe to clean.

    Returns
    -------
    pd.DataFrame
        The cleaned dataframe.
    """
    ...

def display_personal_routines(df: pd.DataFrame, page: int, pages: int): # -> None:
    """Display the routines.

    Parameters
    ----------
    df : pd.DataFrame
        The routines list.
    page : int
        The current page.
    pages : int
        The total number of pages.
    """
    ...

def display_default_routines(df: pd.DataFrame): # -> None:
    """Display the default routines.

    Parameters
    ----------
    df : pd.DataFrame
        The default routines list.
    """
    ...

