"""
This type stub file was generated by pyright.
"""

import pandas as pd
from openbb_terminal.decorators import log_start_end

"""FinBrain Model"""
__docformat__ = ...
logger = ...
@log_start_end(log=logger)
def get_sentiment(symbol: str) -> pd.DataFrame:
    """Gets Sentiment analysis provided by FinBrain's API [Source: finbrain].

    Parameters
    ----------
    symbol : str
        Ticker symbol to get the sentiment analysis from

    Returns
    -------
    pd.DataFrame
        Empty if there was an issue with data retrieval
    """
    ...

