"""
This type stub file was generated by pyright.
"""

import pandas as pd
from openbb_terminal.decorators import log_start_end

"""Runa Model"""
logger = ...
SORT_COLUMNS = ...
@log_start_end(log=logger)
def get_startups() -> pd.DataFrame:
    """Get startups from ROSS index [Source: https://runacap.com/].

    Returns
    -------
    pd.DataFrame
        list of startups
    """
    ...

