"""
This type stub file was generated by pyright.
"""

from typing import Optional
from pandas import DataFrame
from openbb_terminal.decorators import log_start_end

logger = ...
api_url = ...
@log_start_end(log=logger)
def get_btc_rainbow(start_date: str = ..., end_date: Optional[str] = ...) -> DataFrame:
    """Get bitcoin price data
    [Price data from source: https://glassnode.com]
    [Inspired by: https://blockchaincenter.net]

    Parameters
    ----------
    start_date : str
        Initial date, format YYYY-MM-DD
    end_date : Optional[str]
        Final date, format YYYY-MM-DD

    Returns
    -------
    pd.DataFrame
        price over time
    """
    ...

