"""
This type stub file was generated by pyright.
"""

from openbb_terminal.decorators import check_api_key, log_start_end

"""Token Terminal View"""
logger = ...
@log_start_end(log=logger)
@check_api_key(["API_TOKEN_TERMINAL_KEY"])
def display_fundamental_metrics(metric: str, category: str = ..., timeline: str = ..., ascend: bool = ..., limit: int = ..., export: str = ..., external_axes: bool = ...): # -> OpenBBFigure | None:
    """Display fundamental metrics [Source: Token Terminal]

    Parameters
    ----------
    metric : str
        The metric of interest. See `get_possible_metrics()` for available metrics.
    category : str
        The category of interest. See `get_possible_categories()` for available categories.
        The default value is an empty string which means that all categories are considered.
    timeline : str
        The category of interest. See `get_possible_timelines()` for available timelines.
    ascend : bool
        Direction of the sort. If True, the data is sorted in ascending order.
    limit : int
        The number of rows to display.
    export : str
        Export dataframe data to csv,json,xlsx file
    external_axes : bool, optional
        Whether to return the figure object or not, by default False
    """
    ...

