"""
This type stub file was generated by pyright.
"""

import pandas as pd
from typing import Any, Dict, Optional
from openbb_terminal.decorators import log_start_end

"""Common Model"""
__docformat__ = ...
logger = ...
DATA_EXAMPLES: Dict[str, str] = ...
file_types = ...
@log_start_end(log=logger)
def load(file: str, sheet_name: Optional[str] = ..., data_files: Optional[Dict[Any, Any]] = ..., data_examples: Optional[Dict[Any, Any]] = ...) -> pd.DataFrame:
    """Load custom file into dataframe.

    Parameters
    ----------
    file: str
        Path to file
    data_files: dict
        Contains all available data files within the Export folder
    data_examples: dict
        Contains all available examples from Statsmodels

    Returns
    -------
    pd.DataFrame
        Dataframe with custom data
    """
    ...

