"""
This type stub file was generated by pyright.
"""

import pandas as pd

"""Helper Function for the openbb sdk function openbb.news()"""
def news(term: str = ..., sources: str = ..., tag=..., source=...) -> pd.DataFrame:
    """Access news from either feedparser or biztoc for a given term or from specified sources

    Parameters
    ----------
    term : str, optional
        Term to sort for, by default ""
    sources : str, optional
        News sources to include, by default ""
    tag : str, optional
        Biztoc only selection for searching by a given tag, by default ""
    source : str, optional
        Data provider, can be either FeedParser or BizToc.  Will default to Biztoc if key is provided

    Returns
    -------
    pd.DataFrame
        DataFrame of news
    """
    ...

