"""
This type stub file was generated by pyright.
"""

from typing import Optional
from openbb_terminal.decorators import log_start_end

""" News View """
__docformat__ = ...
logger = ...
@log_start_end(log=logger)
def display_news(term: str, sources: str = ..., limit: int = ..., export: str = ..., sheet_name: Optional[str] = ..., sort: str = ...): # -> None:
    """Plots news for a given term and source. [Source: Ultima Insights]

    Parameters
    ----------
    term : str
        term to search on the news articles
    sources : str
        sources to exclusively show news from
    limit : int
        number of articles to display
    export : str
        Export dataframe data to csv,json,xlsx file
    sort: str
        the column to sort by
    """
    ...

@log_start_end(log=logger)
def supported_terms() -> list:
    """Returns supported terms for news"""
    ...

