"""
This type stub file was generated by pyright.
"""

import pandas as pd
from openbb_terminal.decorators import log_start_end

""" Ultima News Monitor Model """
__docformat__ = ...
logger = ...
ULTIMA_BASE_URL = ...
NO_API_KEY = ...
@log_start_end(log=logger)
def get_news(term: str = ..., sort: str = ...) -> pd.DataFrame:
    """Get news for a given term and source. [Source: Ultima Insights News Monitor]

    Parameters
    ----------
    term : str
        term to search on the news articles
    sort: str
        the column to sort by

    Returns
    -------
    articles: pd.DataFrame
        term to search on the news articles

    Examples
    --------
    >>> from openbb_terminal.sdk import openbb
    >>> openbb.news()
    """
    ...

@log_start_end(log=logger)
def supported_terms() -> list:
    """Get supported terms for news. [Source: Ultima]

    Returns
    -------
    terms: list
        list of supported terms (tickers)

    """
    ...

@log_start_end(log=logger)
def get_company_info(ticker: str) -> dict:
    """Get company info for a given ticker. [Source: Ultima Insights]

    Parameters
    ----------
    ticker : str
        ticker to search for company info

    Returns
    -------
    company_info: dict
        dictionary of company info
    """
    ...

@log_start_end(log=logger)
def get_top_headlines(ticker: str) -> dict:
    """Get top headlines for a given ticker. [Source: Ultima Insights]

    Parameters
    ----------
    ticker : str
        ticker to get top headlines for

    Returns
    -------
    top_headlines: dict
        dictionary of top headlines
    """
    ...

